import math, json, sys

# Params (tweakable)
P = dict(
    cx=100, cy=100, R=92,          # disc center & radius (viewBox 200)
    r0=3.0,                         # inner start radius of white channel centerline
    Rend=95.0,                      # outer end radius (beyond disc to open edge)
    turns=1.42,                     # number of turns
    w_out=16.0,                     # white channel width at outer end
    w_in=2.5,                       # white channel width at inner end
)

def spiral_centerline(phi0, P, n=400):
    thmax = P['turns']*2*math.pi
    b = (P['Rend']-P['r0'])/thmax
    pts=[]
    for i in range(n+1):
        th = thmax*i/n
        r = P['r0']+b*th
        a = th+phi0
        pts.append((P['cx']+r*math.cos(a), P['cy']+r*math.sin(a), th/thmax))
    return pts

def width_at(t, P):
    # t in 0..1 from inner to outer
    return P['w_in']+(P['w_out']-P['w_in'])*t

def ribbon(phi0, P):
    c = spiral_centerline(phi0, P)
    left=[]; right=[]
    n=len(c)
    for i,(x,y,t) in enumerate(c):
        # tangent
        if i==0: dx,dy = c[1][0]-x, c[1][1]-y
        elif i==n-1: dx,dy = x-c[i-1][0], y-c[i-1][1]
        else: dx,dy = c[i+1][0]-c[i-1][0], c[i+1][1]-c[i-1][1]
        L=math.hypot(dx,dy) or 1
        nx,ny = -dy/L, dx/L
        hw=width_at(t,P)/2
        left.append((x+nx*hw, y+ny*hw))
        right.append((x-nx*hw, y-ny*hw))
    # build closed polygon: left forward + right backward, round caps approximated by polygon density
    pts = left + right[::-1]
    d = "M %.2f %.2f " % pts[0] + " ".join("L %.2f %.2f"%(px,py) for px,py in pts[1:]) + " Z"
    return d, c[0], c[-1], width_at(0,P)/2, width_at(1,P)/2

def cap(center, hw):
    x,y=center[0],center[1]
    return '<circle cx="%.2f" cy="%.2f" r="%.2f" fill="black"/>'%(x,y,hw)

arms=[]
for phi0 in (0.0, math.pi):
    d, inner, outer, hw_in, hw_out = ribbon(phi0, P)
    arms.append('<path d="%s" fill="black"/>'%d)
    arms.append(cap(inner, hw_in))
    arms.append(cap(outer, hw_out))

mask_content = "\n      ".join(arms)
svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200" width="512" height="512">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#3DD9A0"/>
      <stop offset="1" stop-color="#2BB98A"/>
    </linearGradient>
    <mask id="vortex">
      <circle cx="{P['cx']}" cy="{P['cy']}" r="{P['R']}" fill="white"/>
      {mask_content}
    </mask>
  </defs>
  <circle cx="{P['cx']}" cy="{P['cy']}" r="{P['R']}" fill="url(#g)" mask="url(#vortex)"/>
</svg>'''
open('/tmp/spiral/out.svg','w').write(svg)
# also an html with white bg for compare
open('/tmp/spiral/out.html','w').write('<html><body style="margin:0;background:#fff">'+svg+'</body></html>')
print("written")

# --- Emit TypeScript data for the React component (single source of truth) ---
def emit_ts():
    armsd=[]; caps=[]
    for phi0 in (0.0, math.pi):
        d, inner, outer, hw_in, hw_out = ribbon(phi0, P)
        armsd.append(d)
        caps.append((inner[0], inner[1], hw_in))
        caps.append((outer[0], outer[1], hw_out))
    ts = "// AUTO-GENERATED by scripts/gen-spiral.py — do not edit by hand.\n"
    ts += "// Vortix vortex: solid emerald disc minus a white double-spiral channel (true vector).\n"
    ts += f"export const DISC = {{ cx: {P['cx']}, cy: {P['cy']}, r: {P['R']} }} as const;\n"
    ts += "export const CHANNEL_PATHS: string[] = [\n"
    for d in armsd:
        ts += f"  {json.dumps(d)},\n"
    ts += "];\n"
    ts += "export const CHANNEL_CAPS: { cx: number; cy: number; r: number }[] = [\n"
    for (x,y,r) in caps:
        ts += f"  {{ cx: {x:.2f}, cy: {y:.2f}, r: {r:.2f} }},\n"
    ts += "];\n"
    open('/tmp/spiral/spiralData.ts','w').write(ts)
    print("ts emitted")
emit_ts()
